library(cowplot)
library(tidyr)
library(dplyr)

# Import plotting functions
source(file.path(func_path, "plots", "create_combined_plot.r"))
source(file.path(func_path, "plots", "hist_panel.r"))
source(file.path(func_path, "plots", "create_ica_usage_plot.R"))
source(file.path(func_path, "plots", "create_ica_rej.R"))


# Create filter cutoff plots
create_filter_plots <- function(df) {
  filter_plot <- create_combined_plot(
    df = df,
    start_var = "high_pass",
    end_var = "low_pass",
    x_scale = "log",
    custom_breaks = c(0.01, 0.1, 0.5, 1, 20, 40, 80),
    x_label = "Filter Cutoff (Hz)",
    y_label = "Individual Studies"
  )
  return(filter_plot)
}


# Create EEG Acquisition & Preprocessing
eeg_aq_prep <- function(df) {
  
  # Define major reference categories once
  major_categories <- tolower(c(
    "Cz", "Nose", "Linked earlobes", "Linked mastoids",
    "FCz", "Common average", "Fpz", "CMS", "CMS and DRL",
    "unknown", "Laplacian reference", "REST"
  ))

  # Process reference categories
  df_ref <- df %>%
    mutate(across(
      .cols = c(reference_online, reference_offline),
      .fns = ~ case_when(
        tolower(.) %in% major_categories ~ tolower(.),
        TRUE ~ "Other"
      )
    ))

  # Common reference category mapping
  ref_categories <- c(
    "Common average" = "CAR",
    "Linked mastoids" = "LM",
    "Linked earlobes" = "LE",
    "Cz" = "Cz",
    "FCz" = "FCz",
    "Fpz" = "Fpz",
    "CMS" = "CMS",
    "CMS and DRL" = "CMS",
    "Nose" = "Nose",
    "Laplacian reference" = "LAP",
    "REST" = "REST",
    "Other" = "other",
    "unknown" = "unknown"
  )

  # Create individual histogtams for online / offline references
  ref_online <- hist_panel(df_ref, "reference_online",
    x.label = "Reference (online)",
    discrete = TRUE, tilt_labels = TRUE,
    modality_filter = "EEG",
    allowed = ref_categories[c(
      "Common average", "Linked mastoids", "Cz", "FCz",
      "Fpz", "CMS and DRL", "Nose",
      "Linked earlobes", "Other", "unknown"
    )]
  )

  ref_offline <- hist_panel(df_ref, "reference_offline",
    x.label = "Reference (offline)",
    discrete = TRUE, tilt_labels = TRUE,
    modality_filter = "EEG",
    allowed = ref_categories[c(
      "Common average", "Linked mastoids", "Linked earlobes",
      "REST", "Cz", "Laplacian reference", "unknown", "Other"
    )]
  )

  # Create plots for filtering cutoffs, ICA rejection, and ICA usage
  filter_plot <- create_filter_plots(df)
  ica_rej_plot <- create_ica_rej(df)
  ica_usage_plot <- create_ica_usage_plot(df) 

  # Combine reference plots
  ref_plots <- plot_grid(
    ref_online, ref_offline,
    ncol = 1,
    align = "v"
  )

  # Group ica_rej_plot and ica_usage_plot in one row
  bottom_row <- plot_grid(
    ica_rej_plot,
    ica_usage_plot,
    ncol = 2,
    labels = c("D", "E"),
    align = "h",
    rel_widths = c(1, 1)
  )

  # Combine top (ref_plots, filter_plot) and bottom (ica_rej_plot, ica_usage_plot) rows
  top_row <- plot_grid(
    ref_plots, filter_plot,
    ncol = 2,
    labels = c("A", "C"),
    align = "h",
    rel_widths = c(1, 1)
  )

  plot_grid(
    top_row,
    bottom_row,
    ncol = 1,
    rel_heights = c(1, 1)
  )
}

# Here we generate all figures
# Ideally, each panel / figure should be generated by a function that
# accepts the dataframe as the first argument so that the functions could be
# re-used in the Shiny app
make_figures <- function(df, save_path) {

  eeg_aq_prep_plot <- eeg_aq_prep(df)
  
  ggsave(
    filename = file.path(save_path, "eeg_aq_prep_plot.svg"),
    plot = eeg_aq_prep_plot,
    width = 6.85,
    height = 8,
    units = "in",
    dpi = 300,
    device = "svg"
  )
  show(eeg_aq_prep_plot)
}
