make_figures <- function(df, save_path) {
  # Here we generate all figures
  # Ideally, each panel / figure should be generated by a function that 
  # accepts the dataframe as the first argument so that the functions could be
  # re-used in the Shiny app
}